# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "main-dev-terraform-states-backend-terragruntapplication"
    dynamodb_table = "main-dev-terraform-states-backend-terragruntapplication"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "eu-west-1"
  }
}
